time:
  zone-id: ${user.timezone}

api:
  request-id-name: X-Request-ID
  key-header-name: X-API-KEY
  xff-header-name: X-Forwarded-For
  auth-type-key: authType

security:
  jwt:
    access-expiry: 10m
    refresh-expiry: 1d

time-to-live:
  account-name-cache: 30d
  verification:
    rate-limit: 1h
    code: 5m
    verified: 1h

verification:
  max-code-request: 5

pagination:
  default-page: 0
  default-size: 10

mail:
  from:
    no-reply: no-reply@posty.com

media:
  file-api-url: ${FILE_API_URL}
  file-api-token: ${FILE_API_TOKEN}
  upload-queue-name: media-upload-queue
  delete-queue-name: media-delete-queue

scheduler:
  account:
    deletion:
      grace-period-days: 1
      cron: "0 5 0 * * *"
  media:
    retry:
      upload:
        max-attempt-count: 2
        cron: "0 15 0/3 * * *"
      delete:
        max-attempt-count: 2
        cron: "0 45 1,4,7,10,13,16,19,22 * * *"

server:
  port: 15793
  ssl:
    enabled: true
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}
  error:
    include-stacktrace: never

spring:
  application:
    name: posting-api
  jackson:
    time-zone: ${user.timezone}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  task:
    scheduling:
      pool:
        size: 2
  web:
    locale: ${user.language}
    locale-resolver: fixed
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
  jmx:
    enabled: false

springdoc:
  packages-to-scan: com.posty.postingapi.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
  override-with-generic-response: false