api:
  external-url: ${API_EXTERNAL_URL}
  token: ${API_TOKEN}

directory:
  temp: ${TEMP_PATH}
  base: ${BASE_PATH}

download:
  connect-timeout: 5000 #ms
  read-timeout: 10000 #ms

validation:
  max-size: 10 #MB

clamav:
  host: ${CLAMAV_HOST}
  port: 3310

server:
  port: 12684
  forward-headers-strategy: framework
  ssl:
    enabled: false
  error:
    include-stacktrace: never

spring:
  application:
    name: file-api
  jmx:
    enabled: false