api:
  token: ${API_TOKEN}

directory:
  temp: ${TEMP_PATH}
  base: ${BASE_PATH}

download:
  connect-timeout: 5000 #ms
  read-timeout: 10000 #ms

validation:
  max-size: 10 #MB

clamav:
  host: ${CLAMAV_HOST}
  port: 3310

server:
  port: 12684
  ssl:
    enabled: false
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}
  error:
    include-stacktrace: never

spring:
  application:
    name: file-api
  jmx:
    enabled: false