name: Deploy to the server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    env:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      HOST: ${{ secrets.SERVER_HOST }}
      KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      PASSPHRASE: ${{ secrets.SERVER_PRIVATE_KEY_PASSPHRASE }}
      HOME_DIR: ${{ secrets.HOME_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Get JAR file name
        id: get-jar
        run: |
          JAR_PATH=$(ls build/*.jar | sort -r | head -n 1)
          echo "jar_path=${JAR_PATH}" >> "$GITHUB_OUTPUT"

      - name: Copy JAR to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.KEY }}
          passphrase: ${{ env.PASSPHRASE }}
          source: ${{ steps.get-jar.outputs.jar_path }}
          target: ${{ env.HOME_DIR }}/

      - name: Run deploy script on the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.KEY }}
          script: |
            set -e
            cd ${{ env.HOME_DIR }}
            ln -sf ${{ steps.get-jar.outputs.jar_path }} posting-api
            sudo systemctl restart posting-api.service