name: Deploy posting-api to the server

on:
  push:
    paths:
      - 'posting-api/**'
      - '.github/workflows/posting-api-deploy.yml'
    branches:
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: posting-api

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
    env:
      DEPENDENCY_MODULE: :common:clean :common:build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build ${{ env.SERVICE_NAME }} module
        run: ./gradlew ${{ env.DEPENDENCY_MODULE }} :${{ env.SERVICE_NAME }}:clean :${{ env.SERVICE_NAME }}:build

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "${{ env.SERVICE_NAME }} Test Results #${{ github.run_id }}"
          path: ${{ env.SERVICE_NAME }}/build/test-results/test/*.xml
          reporter: java-junit

      - name: Upload ${{ env.SERVICE_NAME }} JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE_NAME }}-jar
          path: ${{ env.SERVICE_NAME }}/build/*.jar

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    env:
      DEPLOY_USER: ${{ vars.POSTINGAPI_DEPLOY_USER }}
      HOST: ${{ vars.POSTINGAPI_SERVER_HOST }}
      PORT: ${{ vars.POSTINGAPI_SERVER_PORT }}
      KEY: ${{ secrets.POSTINGAPI_SERVER_PRIVATE_KEY }}
      PASSPHRASE: ${{ secrets.POSTINGAPI_SERVER_PRIVATE_KEY_PASSPHRASE }}
      HOME_DIR: ${{ vars.POSTINGAPI_HOME_DIR }}

    steps:
      - name: Download ${{ env.SERVICE_NAME }} JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SERVICE_NAME }}-jar
          path: ${{ env.SERVICE_NAME }}/build

      - name: Get JAR file name
        id: get-jar
        run: |
          JAR_FILENAME=$(ls ${{ env.SERVICE_NAME }}/build/*.jar | sort -r | head -n 1 | xargs -n 1 basename)
          echo "JAR_FILENAME=$JAR_FILENAME" >> $GITHUB_ENV

      - name: Debug JAR path
        run: |
          echo "üìå Checking if file exists: ${{ env.SERVICE_NAME }}/build/${{ env.JAR_FILENAME }}"
          ls -al ${{ env.SERVICE_NAME }}/build/
          if [ -f "${{ env.SERVICE_NAME }}/build/${{ env.JAR_FILENAME }}" ]; then
            echo "‚úÖ File exists"
          else
            echo "‚ùå File does not exist"
            exit 1
          fi

      - name: Copy ${{ env.SERVICE_NAME }} JAR to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.KEY }}
          passphrase: ${{ env.PASSPHRASE }}
          source: ${{ env.SERVICE_NAME }}/build/${{ env.JAR_FILENAME }}
          target: ${{ env.HOME_DIR }}/jars/
          strip_components: 2

      - name: Run deploy script on the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.KEY }}
          passphrase: ${{ env.PASSPHRASE }}
          script: |
            set -e
            cd ${{ env.HOME_DIR }}
            ln -sf jars/${{ env.JAR_FILENAME }} ${{ env.SERVICE_NAME }}
            echo "üìå Creating symlink..."
            if [ ! -L ${{ env.SERVICE_NAME }} ]; then
              echo "‚ùå Symlink creation failed"
              exit 1
            fi
              echo "‚úÖ Symlink created successfully"
            echo "üìå Restarting service..."
            if sudo systemctl restart ${{ env.SERVICE_NAME }}.service; then
              echo "‚úÖ Service restarted"
            else
              echo "‚ùå Failed to restart the service"
              exit 1
            fi
            if sudo systemctl status ${{ env.SERVICE_NAME }}.service | grep -q "Active: active"; then
              echo "‚úÖ Service is active"
            else
              echo "‚ùå Service is not active"
              exit 1
            fi