name: Deploy posting-api to the server

on:
  push:
    paths:
      - 'posting-api/**'
      - '.github/workflows/posting-api-deploy.yml'
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build posting-api module
        run: ./gradlew :common:clean :common:build :posting-api:clean :posting-api:build -x test

      - name: Upload posting-api JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: posting-api-jar
          path: posting-api/build/*.jar

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    env:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      HOST: ${{ secrets.SERVER_HOST }}
      KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      PASSPHRASE: ${{ secrets.SERVER_PRIVATE_KEY_PASSPHRASE }}
      HOME_DIR: ${{ secrets.HOME_DIR }}

    steps:
      - name: Download posting-api JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: posting-api-jar
          path: posting-api/build

      - name: Get JAR file name
        id: get-jar
        run: |
          JAR_FILENAME=$(ls posting-api/build/*.jar | sort -r | head -n 1 | xargs -n 1 basename)
          echo "JAR_FILENAME=$JAR_FILENAME" >> $GITHUB_ENV

      - name: Debug JAR path
        run: |
          echo "üìå Checking if file exists: posting-api/build/${{ env.JAR_FILENAME }}"
          ls -al posting-api/build/
          if [ -f "posting-api/build/${{ env.JAR_FILENAME }}" ]; then
            echo "‚úÖ File exists"
          else
            echo "‚ùå File does not exist"
            exit 1
          fi

      - name: Copy posting-api JAR to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.KEY }}
          passphrase: ${{ env.PASSPHRASE }}
          source: posting-api/build/${{ env.JAR_FILENAME }}
          target: ${{ env.HOME_DIR }}/jars/
          strip_components: 2

      - name: Run deploy script on the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.KEY }}
          passphrase: ${{ env.PASSPHRASE }}
          script: |
            set -e
            cd ${{ env.HOME_DIR }}
            ln -sf jars/${{ env.JAR_FILENAME }} posting-api
            echo "üìå Creating symlink..."
            if [ ! -L posting-api ]; then
              echo "‚ùå Symlink creation failed"
              exit 1
            fi
              echo "‚úÖ Symlink created successfully"
            echo "üìå Restarting service..."
            if sudo systemctl restart posting-api.service; then
              echo "‚úÖ Service restarted"
            else
              echo "‚ùå Failed to restart the service"
              exit 1
            fi
            if sudo systemctl status posting-api.service | grep -q "Active: active"; then
              echo "‚úÖ Service is active"
            else
              echo "‚ùå Service is not active"
              exit 1
            fi